title = "Styx Configuration File"

[server]
port = 8088
server_name = "my_url"

[Default]
default_route = "amazon.com"
alive = true
weight = 1

[[sites]]
name = "google"
entrypoint = "localhost:8088"
addresses = [ "http://google.com", "http://youtube.com"]
alives = [true, true]
weights = [1, 1]


[[sites]]
name = "localhost"
entrypoint = "127.0.0.1:8088"
addresses = [ "http://facebook.com", "http://twitter.com"]
alives = [true, true]
weights = [1, 1]


[DDOS_Parameters]
refresh_request_rate = 50 # rate request allow per second
max_request_per_user = 100
verification_timer = 180 # in seconds